name: PR Checklist
on:
  pull_request:
    types: [opened]
jobs:
  fyi:
    name: Posts a PR checklist
    runs-on: [self-hosted, Lms, Linux]
    timeout-minutes: 2
    steps:
      - uses: Brightspace/third-party-actions@actions/github-script
        # Do this at the step level so that the job shows as passing in the PR
        # UI (which is less distracting than cancelled)
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
            ## Team USA PR Checklist:
            
            **Did you use a semver keyword in a commit message?**
            - [ ] Yes I used one in at least one of my commits
            - [ ] No but I use a semver keyword in the commit message when I merge and squash
            
            **Did you paste the Rally US URL in the description?**
            - [ ] Yes
            - [ ] No as there's no corresponding Rally US
              `
            })
